version: "3.7"

services:

  shop:
    container_name: shopware
    build:
        context: ./docker
        dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MOLLIE_API_KEY=test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MOLLIE_WEBHOOK_DOMAIN=local-test.mollie.com