name: Release Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

env:
  IMG_NAME: boxblinkracer/shopware6-mollie:latest


jobs:

  build:
    name: Build and push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
            - name: amd64
              platform: linux/amd64
            - name: arm64
              platform: linux/arm64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ env.IMG_NAME }}-${{ matrix.name }} --build-arg ARCH=${{ matrix.platform }} docker
          docker push ${{ env.IMG_NAME }}-${{ matrix.name }}

  manifest:
    name: Create and push manifest
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest ${{ env.IMG_NAME }}
        run: |
          docker manifest create ${{ env.IMG_NAME }} --amend ${{ env.IMG_NAME }}-amd64 --amend ${{ env.IMG_NAME }}-arm64
          docker manifest push ${{ env.IMG_NAME }}
