name: Release Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:

  build:
    name: Trigger CircleCI
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        run: cd .circleci && sh trigger.sh ${{ secrets.CIRCLE_CI_TOKEN }}

